spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        #default_batch_fetch_size >> 페이징 처리 할 때 좋음
        #OneToMany 관계에서 컬렉션 만큼 계속 쿼리를 내보내는데 해당 옵션을 사용한다면 in()으로 쿼리를 만들어줌
        #저 위의 숫자는 in에 들어갈 최대 갯수
        #만약 10으로 설정되어 있느데 100개라면 in에 10개씩 10번 쿼리가 호출 되는 것
        #size는 100~1000 사이로 하는것이 좋다

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
